### ISSUE TITLE
Akash Tests Failing: Invalid Bech32 Prefix

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/relayer#11]
In the Akash to Gaia based testing there is an error that occurs nearly 70% of the time. 
`SendTransferMsg()` fails in `relayer_akash_test.go` with the following output to stderr

```
--- FAIL: TestAkashToGaiaStreamingRelayer (36.22s)
panic: invalid Bech32 prefix; expected cosmos, got akash [recovered]
	panic: invalid Bech32 prefix; expected cosmos, got akash

goroutine 39 [running]:
testing.tRunner.func1.2(0x1618b40, 0xc001a39080)
	/usr/lib/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000603e00)
	/usr/lib/go/src/testing/testing.go:1146 +0x4b6
panic(0x1618b40, 0xc001a39080)
	/usr/lib/go/src/runtime/panic.go:965 +0x1b9
github.com/cosmos/ibc-go/modules/apps/transfer/types.MsgTransfer.GetSigners(...)
	/home/anon/go/pkg/mod/github.com/cosmos/ibc-go@v1.0.1/modules/apps/transfer/types/msgs.go:82
github.com/cosmos/cosmos-sdk/types/tx.(*Tx).GetSigners(0xc001a1bbf0, 0x29, 0xc0016251a0, 0x29)
	/home/anon/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/types/tx/types.go:103 +0x118
github.com/cosmos/cosmos-sdk/x/auth/tx.(*wrapper).GetSigners(0xc001a1f200, 0x28, 0x28, 0x1)
	/home/anon/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/x/auth/tx/builder.go:100 +0x2e
github.com/cosmos/cosmos-sdk/client/tx.checkMultipleSigners(0xc000000001, 0x1c0da98, 0xc001a1f200, 0x0, 0xc0010d6ec0)
	/home/anon/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/client/tx/tx.go:375 +0x50
github.com/cosmos/cosmos-sdk/client/tx.Sign(0x1c11b48, 0xc00127e200, 0x1c0b858, 0xc00127e240, 0x1bffa68, 0x269a0e0, 0x1, 0x8, 0x15d47, 0x0, ...)
	/home/anon/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/client/tx/tx.go:397 +0x7f
github.com/cosmos/relayer/relayer.(*Chain).SendMsgs(0xc001266640, 0xc001a38bf0, 0x1, 0x1, 0x1, 0xc001a38bf0, 0x0, 0x1)
	/home/anon/go/src/github.com/strangelove-ventures/relayer/relayer/chain.go:326 +0x405
github.com/cosmos/relayer/relayer.(*RelayMsgs).SendWithController(0xc0010d7d88, 0xc001266640, 0xc001266500, 0x1)
	/home/anon/go/src/github.com/strangelove-ventures/relayer/relayer/relayMsgs.go:157 +0x488
github.com/cosmos/relayer/relayer.(*RelayMsgs).Send(...)
	/home/anon/go/src/github.com/strangelove-ventures/relayer/relayer/relayMsgs.go:66
github.com/cosmos/relayer/relayer.(*Chain).SendTransferMsg(0xc001266640, 0xc001266500, 0x1827cc3, 0x9, 0xc0001d7ee0, 0xc0001de420, 0x2d, 0x0, 0x0, 0x0, ...)
	/home/anon/go/src/github.com/strangelove-ventures/relayer/relayer/packet-tx.go:47 +0x1b4
github.com/cosmos/relayer/test.TestAkashToGaiaStreamingRelayer(0xc000603e00)
	/home/anon/go/src/github.com/strangelove-ventures/relayer/test/relayer_akash_test.go:72 +0xe9f
testing.tRunner(0xc000603e00, 0x1a6f388)
	/usr/lib/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1238 +0x2b3
FAIL	github.com/cosmos/relayer/test	36.292s
FAIL
make: *** [/home/anon/go/src/github.com/strangelove-ventures/relayer/Makefile:66: test] Error 1
```

**Comment by jtieri** [comment]
Opened an issue in the `cosmos/relayer` repo to address the remaining Bech32 errors that remain in the [relayer](https://github.com/cosmos/relayer/issues/545). 
Gonna go ahead and close this out
